[book]
authors = [
    "Andreas Schaeffer"
]
language = "en"
src = "src"
title = "mdbook-preprocessor-graphql-playground"

[preprocessor.graphql-playground]
command = "mdbook-graphql-playground"
renderer = ["html"]

[output]

[output.html]
additional-js = ["././graphql-playground-react-middleware.js", "././graphql-playground.js"]
additional-css = ["././graphql-playground.css"]
